title = "store"

[[meal_time]]
  start = 6
  end = 8
  zh = "早饭"
[[meal_time]]
  start = 11
  end = 13
  zh = "午饭"
[[meal_time]]
  start = 18
  end = 20
  zh = "晚饭"

[[cleaning]]
  en = "air_conditioner"
  zh = "空调滤网清洁"
  tip = "代码垃圾回收，空调也需要。要不你哪天就Stop the world了！"
[[yearly]]
  en = "toothwash"
  zh = "洗牙"
  tip = "没半年到一年花半小时Full GC一下，防止哪天Out of Mermory。"
[[yearly]]
  en = "checkup"
  zh = "体检"
  tip = "代码过单元测试，人也需要。别忘了每年体检。"

[pool]
  vegetable = [
    "broccoli 西蓝花",
    "lettuce 生菜",
    "romaine lettuce 油麦菜",
    "pinach 菠菜",
    "asparagus 芦笋",
    " 四季豆",
    " 荷兰豆",
    " 白菜",
    " 花菜",
    " 卷心菜",
    " 胡萝卜",
    " 南瓜",
    " 芥菜",
    " 荠菜",
    " 芥兰",
    " 芹菜",
  ]

  movement = [
    "俯卧撑（做不了可以对墙做）",
    "静力桥",
    "举腿",
    "深蹲",
    "小燕飞",
    "提肛"
  ]

  fruit = [
    "柚子",
    "圣女果",
    "苹果",
    "橘子",
    "樱桃",

  ]

  drink = [
    "无糖拿铁（乳糖不耐受请喝无糖美式）",
    "茶",
    "白开水",
    "牛奶（乳糖不耐受请重新随机）"
  ]

  game = [
    "你TM还想玩游戏，身体不好，没有女朋友，又没钱。马斯克火箭都快打到火星了！",
  ]

  outing_dest.hangzhou = [
    "太子湾公园",
    "湘湖",
    "灵隐寺",
    "龙井村和九溪十八涧",
    "西溪湿地",
    "浙江大学之江校区",
    "云栖竹径（Bamboo-lined path at yunqi）",
    "满陇桂雨（Sweet osmanthus rain at manjuelong village）",
    "虎跑梦泉（Dreaming of tiger spring at hupao valley）"
  ]


